from __future__ import annotations

import os
import re
import stat
import subprocess
from pathlib import Path

from admin import crypto, db
from admin.settings import (
    DOCKER_COMPOSE,
    PGBOUNCER_INI,
    PGBOUNCER_LISTEN_PORT,
    PGPASS_CONTAINER_PATH,
    PGPASS_FILE,
    RUNTIME_DIR,
    USERLIST_TXT,
)


_CONN_SAFE = re.compile(r"^[\w.+-]+$")


def _conn_value(value: str) -> str:
    s = str(value).strip().strip("\r")
    if _CONN_SAFE.match(s):
        return s
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _pgpass_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace(":", "\\:")


def _pgpass_line(host: str, port: int, database: str, user: str, password: str) -> str:
    return ":".join(
        [
            _pgpass_escape(host),
            str(port),
            _pgpass_escape(database),
            _pgpass_escape(user),
            _pgpass_escape(password.strip().strip("\r")),
        ]
    )


def _backend_conn_str(host: str, port: int, database: str, user: str) -> str:
    """Пароль не в ini — только passfile (как у psql/.pgpass), иначе PgBouncer может исказить password=."""
    return (
        f"host={_conn_value(host)} "
        f"port={port} "
        f"dbname={_conn_value(database)} "
        f"user={_conn_value(user)} "
        f"passfile={PGPASS_CONTAINER_PATH}"
    )


def _server_tls_sslmode(rows: list) -> str | None:
    for row in rows:
        if (row["sslmode"] or "disable") == "require":
            return "require"
    return None


def generate_configs() -> None:
    db.init_db()
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)

    database_lines: list[str] = []
    userlist_lines: list[str] = []
    pgpass_lines: list[str] = []
    pgpass_seen: set[str] = set()

    with db.connect() as conn:
        rows = conn.execute(
            """
            SELECT u.username, u.pool_name, u.auth_md5,
                   s.host, s.port, s.database, s.user, s.password_enc, s.sslmode
            FROM pgbouncer_users u
            JOIN postgres_servers s ON s.id = u.postgres_server_id
            ORDER BY u.pool_name
            """
        ).fetchall()

    server_tls = _server_tls_sslmode(rows)

    for row in rows:
        pg_password = crypto.decrypt_secret(row["password_enc"], db.storage_key())
        conn_str = _backend_conn_str(
            row["host"],
            row["port"],
            row["database"],
            row["user"],
        )
        database_lines.append(f"{row['pool_name']} = {conn_str}")
        userlist_lines.append(f'"{row["username"]}" "{row["auth_md5"]}"')

        pline = _pgpass_line(
            row["host"], row["port"], row["database"], row["user"], pg_password
        )
        if pline not in pgpass_seen:
            pgpass_seen.add(pline)
            pgpass_lines.append(pline)

        if os.environ.get("PGB_DEBUG_LOG_PASSWORDS") == "1":
            print(
                f"[PGB_DEBUG] {row['pool_name']}: user={row['user']} "
                f"password_len={len(pg_password.strip())} (в pgpass, не в ini)",
                flush=True,
            )

    tls_line = f"server_tls_sslmode = {server_tls}\n" if server_tls else ""

    ini_body = f""";; Generated by pgbouncer-admin — do not edit manually while using the admin UI

[databases]
{chr(10).join(database_lines) if database_lines else "; add pools via admin UI"}

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = {PGBOUNCER_LISTEN_PORT}
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt
{tls_line}pool_mode = transaction
verbose = 1
log_pooler_errors = 1
max_client_conn = 1000
default_pool_size = 20
min_pool_size = 0
reserve_pool_size = 5
server_reset_query = DISCARD ALL
ignore_startup_parameters = extra_float_digits

[users]
"""

    USERLIST_TXT.write_text(
        ("\n".join(userlist_lines) + "\n") if userlist_lines else "\n",
        encoding="utf-8",
        newline="\n",
    )
    PGBOUNCER_INI.write_text(ini_body, encoding="utf-8", newline="\n")

    pgpass_body = "\n".join(pgpass_lines) + ("\n" if pgpass_lines else "")
    PGPASS_FILE.write_text(pgpass_body, encoding="utf-8", newline="\n")
    if pgpass_lines:
        PGPASS_FILE.chmod(stat.S_IRUSR | stat.S_IWUSR)


def reload_pgbouncer() -> tuple[bool, str]:
    try:
        result = subprocess.run(
            [*DOCKER_COMPOSE.split(), "exec", "-T", "pgbouncer", "kill", "-HUP", "1"],
            capture_output=True,
            text=True,
            timeout=15,
            cwd=Path(PGBOUNCER_INI).parents[1],
        )
        if result.returncode == 0:
            return True, "RELOAD OK (SIGHUP)"
        return False, (result.stderr or result.stdout or "reload failed").strip()
    except FileNotFoundError:
        return False, "docker compose not found"
    except subprocess.TimeoutExpired:
        return False, "reload timed out"


def apply_and_reload() -> tuple[bool, str]:
    generate_configs()
    ok, msg = reload_pgbouncer()
    if not ok:
        return False, f"config written; reload: {msg}"
    return True, msg


def ensure_bootstrap_configs() -> None:
    db.init_db()
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    if not PGBOUNCER_INI.exists():
        generate_configs()
