from __future__ import annotations

import subprocess
from pathlib import Path

from admin import crypto, db
from admin.settings import (
    DOCKER_COMPOSE,
    PGBOUNCER_INI,
    PGBOUNCER_LISTEN_PORT,
    RUNTIME_DIR,
    USERLIST_TXT,
)


def _escape_ini_value(value: str) -> str:
    return value.replace("\\", "\\\\").replace(" ", "\\ ")


def generate_configs() -> None:
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)

    database_lines: list[str] = []
    userlist_lines: list[str] = []

    with db.connect() as conn:
        rows = conn.execute(
            """
            SELECT u.username, u.pool_name, u.auth_md5,
                   s.host, s.port, s.database, s.user, s.password_enc
            FROM pgbouncer_users u
            JOIN postgres_servers s ON s.id = u.postgres_server_id
            ORDER BY u.pool_name
            """
        ).fetchall()

    for row in rows:
        pg_password = crypto.decrypt_secret(row["password_enc"], db.storage_key())
        conn_str = (
            f"host={row['host']} port={row['port']} dbname={row['database']} "
            f"user={row['user']} password={pg_password}"
        )
        database_lines.append(f"{row['pool_name']} = {_escape_ini_value(conn_str)}")
        userlist_lines.append(f'"{row["username"]}" "{row["auth_md5"]}"')

    ini_body = f""";; Generated by pgbouncer-admin — do not edit manually while using the admin UI

[databases]
{chr(10).join(database_lines) if database_lines else "; add pools via admin UI"}

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = {PGBOUNCER_LISTEN_PORT}
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 20
min_pool_size = 0
reserve_pool_size = 5
server_reset_query = DISCARD ALL
ignore_startup_parameters = extra_float_digits

[users]
"""

    USERLIST_TXT.write_text(
        ("\n".join(userlist_lines) + "\n") if userlist_lines else "\n",
        encoding="utf-8",
    )
    PGBOUNCER_INI.write_text(ini_body, encoding="utf-8")


def reload_pgbouncer() -> tuple[bool, str]:
    """SIGHUP reload — no admin console credentials required."""
    try:
        result = subprocess.run(
            [*DOCKER_COMPOSE.split(), "exec", "-T", "pgbouncer", "kill", "-HUP", "1"],
            capture_output=True,
            text=True,
            timeout=15,
            cwd=Path(PGBOUNCER_INI).parents[1],
        )
        if result.returncode == 0:
            return True, "RELOAD OK (SIGHUP)"
        return False, (result.stderr or result.stdout or "reload failed").strip()
    except FileNotFoundError:
        return False, "docker compose not found"
    except subprocess.TimeoutExpired:
        return False, "reload timed out"


def apply_and_reload() -> tuple[bool, str]:
    generate_configs()
    ok, msg = reload_pgbouncer()
    if not ok:
        return False, f"config written; reload: {msg}"
    return True, msg


def ensure_bootstrap_configs() -> None:
    if not PGBOUNCER_INI.exists():
        generate_configs()
